championMappings = {
    "aurelionsol": "Aurelion Sol",
    "blitz-crank": "Blitzcrank",
    "chogath": "ChoGath",
    "cho'gath": "ChoGath",
    "drmundo": "Dr. Mundo",
    "mundo": "Dr. Mundo",
    "dr mundo": "Dr. Mundo",
    "dr.mundo": "Dr. Mundo",
    "jarvan": "Jarvan IV",
    "karvan4": "Jarvin IV",
    "kaisa": "Kai'Sa",
    "khazix": "Kha'Zix",
    "kogmaw": "Kog'Maw",
    "leesin": "Lee Sin",
    "masteryi": "Master Yi",
    "missfortune": "Miss Fortune",
    "nunu": "Nunu & Willump",
    "nunu and willump": "Nunu & Willump",
    "willump": "Nunu & Willump",
    "reksai": "Rek'Sai",
    "tahmkench": "Tahm Kench",
    "tahm": "Tahm Kench",
    "kench": "Kench",
    "twistedfate": "Twisted Fate",
    "velkoz": "Vel'Koz",
    "vel koz": "Vel'Koz",
    "xinzhao": "Xin Zhao"
}
exports.mappings = championMappings;
