championImages = {
    "Aatrox": "../img/champion_loading_images_cropped/Aatrox.png",
    "Ahri": "../img/champion_loading_images_cropped/Ahri.png",
    "Akali": "/img/champion_loading_images_cropped/Akali.PNG",
    "Alistar": "../img/champion_loading_images_cropped/Alistar.png",
    "Amumu": "../",
    "Anivia": "../img/champion_loading_images_cropped/Anivia.png",
    "Annie": "../img/champion_loading_images_cropped/Annie.png",
    "Aphelios": "../img/champion_loading_images_cropped/Aphelios.png",
    "Ashe": "../img/champion_loading_images_cropped/Ashe.png",
    "Aurelion Sol": "../img/champion_loading_images_cropped/Aurelion Sol.png",
    "Azir": "../img/champion_loading_images_cropped/Azir.png",
    "Bard": "../img/champion_loading_images_cropped/Bard.png",
    "Blitzcrank": "../img/champion_loading_images_cropped/Blitzcrank.png",
    "Brand": "../img/champion_loading_images_cropped/Brand.png",
    "Braum": "../img/champion_loading_images_cropped/Braum.png",
    "Caitlyn": "../img/champion_loading_images_cropped/Caitlyn.png",
    "Camille": "../img/champion_loading_images_cropped/Camille.png",
    "Cassiopeia": "../img/champion_loading_images_cropped/Cassiopeia.png",
    "Cho'Gath": "../img/champion_loading_images_cropped/Cho'Gath.png",
    "Corki": "../img/champion_loading_images_cropped/Corki.png",
    "Darius": "../img/champion_loading_images_cropped/Darius.png",
    "Diana": "../img/champion_loading_images_cropped/Diana.png",
    "DJ Sona": "../",
    "Dr. Mundo": "../",
    "Draven": "../img/champion_loading_images_cropped/Draven.png",
    "Ekko": "../img/champion_loading_images_cropped/Ekko.png",
    "Elise": "../img/champion_loading_images_cropped/Elise.png",
    "Evelynn": "../",
    "Ezreal": "../img/champion_loading_images_cropped/Ezreal.png",
    "Fiddlesticks": "../img/champion_loading_images_cropped/Fiddlesticks.png",
    "Fiora": "../img/champion_loading_images_cropped/Fiora.png",
    "Fizz": "../img/champion_loading_images_cropped/Fizz.png",
    "Galio": "../img/champion_loading_images_cropped/Galio.png",
    "Gangplank": "../img/champion_loading_images_cropped/Gangplank.png",
    "Garen": "../img/champion_loading_images_cropped/Garen.png",
    "Gnar": "../img/champion_loading_images_cropped/Gnar.png",
    "Gragas": "../img/champion_loading_images_cropped/Gragas.png",
    "Graves": "../img/champion_loading_images_cropped/Graves.png",
    "Hecrim": "img/champion_loading_images_cropped/Hecarim.png",
    "Heimerdinger": "../img/champion_loading_images_cropped/Heimerdinger.png",
    "Illaoi": "../img/champion_loading_images_cropped/Illaoi.png",
    "Irelia": "../img/champion_loading_images_cropped/Irelia.png",
    "Ivern": "../img/champion_loading_images_cropped/Ivern.png",
    "Janna": "../img/champion_loading_images_cropped/Janna.png",
    "Jarvan IV": "../img/champion_loading_images_cropped/Jarvin IV.png",
    "Jax": "../img/champion_loading_images_cropped/Jax.png",
    "Jayce": "../img/champion_loading_images_cropped/Jayce.png",
    "Jhin": "../img/champion_loading_images_cropped/Jhin.png",
    "Jinx": "../img/champion_loading_images_cropped/Jinx.png",
    "Kai'Sa": "../img/champion_loading_images_cropped/Kai'Sa.png",
    "Kalista": "../img/champion_loading_images_cropped/Kalista.png",
    "Karma": "../img/champion_loading_images_cropped/Karma.png",
    "Karthus": "../img/champion_loading_images_cropped/Karthus.png",
    "Kassadin": "../img/champion_loading_images_cropped/Kassadin.png",
    "Katarina": "../img/champion_loading_images_cropped/Katarina.png",
    "Kayle": "../img/champion_loading_images_cropped/Kayle.png",
    "Kayn": "../img/champion_loading_images_cropped/Kayn.png",
    "Kennen": "../img/champion_loading_images_cropped/Kennen.png",
    "Kha'Zix": "../img/champion_loading_images_cropped/Kha'zix.png",
    "Kindred": "../img/champion_loading_images_cropped/Kindred.png",
    "Kled": "../img/champion_loading_images_cropped/Kled.png",
    "Kog'Maw": "../img/champion_loading_images_cropped/Kog'Maw.png",
    "LeBlanc": "../img/champion_loading_images_cropped/LeBlanc.png",
    "Lee Sin": "../img/champion_loading_images_cropped/Lee Sin.png",
    "Leona": "../img/champion_loading_images_cropped/Leona.png",
    "Lissandra": "../img/champion_loading_images_cropped/Lissandra.png",
    "Lucian": "../img/champion_loading_images_cropped/Lucian.png",
    "Lulu": "../img/champion_loading_images_cropped/Lulu.png",
    "Lux": "../img/champion_loading_images_cropped/Lux.png",
    "Malphite": "img/champion_loading_images_cropped/Malphite.png",
    "Malzahar": "../img/champion_loading_images_cropped/Malzahar.png",
    "Maokai": "../img/champion_loading_images_cropped/Maokai.png",
    "Master Yi": "../img/champion_loading_images_cropped/Master Yi.png",
    "Miss Fortune": "../img/champion_loading_images_cropped/Miss Fortune.png",
    "Mordekaiser": "../img/champion_loading_images_cropped/Mordekaiser.png",
    "Morgana": "../img/champion_loading_images_cropped/Nami.png",
    "Nami": "../img/champion_loading_images_cropped/Nami.png",
    "Nasus": "../img/champion_loading_images_cropped/Nasus.png",
    "Nautilus": "../img/champion_loading_images_cropped/Nautilus.png",
    "Neeko": "../img/champion_loading_images_cropped/Neeko.png",
    "Nidalee": "../img/champion_loading_images_cropped/Nidalee.png",
    "Nocturn": "../img/champion_loading_images_cropped/Nocturne.png",
    "Nunu & Willump": "../img/champion_loading_images_cropped/Nunu & Willump.png",
    "Olaf": "../img/champion_loading_images_cropped/Olaf.png",
    "Orianna": "../img/champion_loading_images_cropped/Orianna.png",
    "Ornn": "../img/champion_loading_images_cropped/Ornn.png",
    "Pantheon": "../img/champion_loading_images_cropped/Ornn.png",
    "Poppy": "../img/champion_loading_images_cropped/Poppy.png",
    "Pyke": "../img/champion_loading_images_cropped/Pyke.png",
    "Qiyana": "../img/champion_loading_images_cropped/Qiyana.png",
    "Quinn": "../img/champion_loading_images_cropped/Quinn.png",
    "Rakan": "../img/champion_loading_images_cropped/Rakan.png",
    "Rammus": "../img/champion_loading_images_cropped/Rammus.png",
    "Rek'Sai": "../img/champion_loading_images_cropped/Rek'Sai.png",
    "Renekton": "../img/champion_loading_images_cropped/Renekton.png",
    "Rengar": "../img/champion_loading_images_cropped/Rengar.png",
    "Riven": "../img/champion_loading_images_cropped/Riven.png",
    "Rumble": "../img/champion_loading_images_cropped/Rumble.png",
    "Ryze": "../img/champion_loading_images_cropped/Ryze.png",
    "Sejuani": "../img/champion_loading_images_cropped/Sejuani.png",
    "Senna": "../img/champion_loading_images_cropped/Senna.png",
    "Sett": "../img/champion_loading_images_cropped/Sett.png",
    "Shaco": "../img/champion_loading_images_cropped/Shaco.png",
    "Shen": "../img/champion_loading_images_cropped/Shen.png",
    "Shyvana": "../img/champion_loading_images_cropped/Shyvana.png",
    "Singed": "../img/champion_loading_images_cropped/Singed.png",
    "Sion": "../img/champion_loading_images_cropped/Sion.png",
    "Sivir": "../",
    "Skarner": "../",
    "Sona": "../",
    "Soraka": "../",
    "Swain": "../",
    "Sylas": "../",
    "Syndra": "../",
    "Tahm Kench": "../",
    "Taliyah": "../",
    "Talon": "../",
    "Taric": "../",
    "Teemo": "../",
    "Thresh": "../",
    "Tristana": "../",
    "Trundle": "../",
    "Tryndamere": "../",
    "Twisted Fate": "../",
    "Twitch": "../",
    "Udyr": "../",
    "Urgot": "../",
    "Varus": "../",
    "Vayne": "../",
    "Veigar": "../",
    "Vel'Koz": "../",
    "Victor": "../",
    "Vi": "../",
    "Vladimir": "../",
    "Volibear": "../",
    "Warwick": "../",
    "Wukong": "../",
    "Xayah": "../",
    "Xerath": "../",
    "Xin Zhao": "../",
    "Yasuo": "../",
    "Yorick": "../",
    "Yuumi": "../",
    "Zac": "../",
    "Zed": "../",
    "Ziggs": "../",
    "Zilean": "../",
    "Zoe": "../",
    "Zyra": "../"
}

exports.images = championImages;